const topics = [
  "자료구조란 무엇인가요?",
  "배열과 연결 리스트의 차이점은 무엇인가요?",
  "스택과 큐의 기본 개념을 설명해주세요.",
  "트리와 그래프의 차이점은 무엇인가요?",
  "이진 트리와 이진 탐색 트리(BST)의 차이점을 설명하세요.",
  "해시 테이블의 작동 원리는 어떻게 되나요?",
  "해시 충돌이란 무엇이며 어떻게 처리할 수 있나요?",
  "AVL 트리와 레드-블랙 트리와 같은 균형 이진 트리의 목적은 무엇인가요?",
  "그래프 순회 알고리즘 중 깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)에 대해 설명하세요.",
  "힙(heap) 자료구조의 용도와 특징은 무엇인가요?",
  "동적 프로그래밍과 그리디 알고리즘은 어떤 상황에서 사용되나요?",
  "연결 리스트를 사용하여 스택과 큐를 구현하는 방법을 설명하세요.",
  "정렬 알고리즘 중 퀵 정렬과 병합 정렬의 차이점을 설명하세요.",
  "버블 정렬과 선택 정렬과 같은 간단한 정렬 알고리즘에 대해 설명하세요.",
  "자료구조를 선택할 때 어떤 요소들을 고려해야 하나요?",
  "시간 복잡도와 공간 복잡도란 무엇인가요?",
  "시간 복잡도와 공간 복잡도를 왜 고려해야 하나요?",
  "빅 오 표기법(Big O notation)이란 무엇이며 어떻게 사용되나요?",
  "알고리즘의 시간 복잡도를 분석하는 과정을 설명하세요.",
  "최선, 평균, 최악의 경우 시간 복잡도를 설명하세요.",
  "선형 시간 복잡도와 로그 시간 복잡도의 차이점을 설명하세요.",
  "시간 복잡도를 개선하기 위한 방법으로 어떤 것들이 있나요?",
  "공간 복잡도를 개선하기 위한 방법으로 어떤 것들이 있나요?",
  "공간 복잡도 분석을 위해 어떤 도구나 기법을 사용할 수 있나요?",
  "재귀 알고리즘의 시간 복잡도와 공간 복잡도에 대해 설명하세요.",
  "다이내믹 프로그래밍(Dynamic Programming)의 시간 복잡도와 공간 복잡도를 설명하세요.",
  "그리디 알고리즘의 시간 복잡도와 공간 복잡도를 설명하세요.",
  "시간 복잡도와 공간 복잡도를 비교하여 어떤 경우에 어떤 것을 더 중요하게 고려해야 하는지 설명하세요.",
  "최근에 나온 효율적인 알고리즘 또는 자료구조 중 하나를 선택하고 해당 알고리즘의 시간 복잡도와 공간 복잡도를 설명하세요.",
  "알고리즘의 성능을 평가하는 데 시간 복잡도와 공간 복잡도를 어떻게 활용할 수 있을까요?",
  "그래프(Graph)란 무엇이며 어떤 상황에서 사용되나요?",
  "그래프의 기본 요소인 정점(Vertex)과 간선(Edge)에 대해 설명하세요.",
  "방향 그래프와 무방향 그래프의 차이점은 무엇인가요?",
  "가중 그래프(Weighted Graph)와 비가중 그래프(Unweighted Graph)의 차이를 설명하세요.",
  "그래프의 표현 방법으로는 어떤 것들이 있으며 각각의 장단점은 무엇인가요?",
  "인접 행렬(Adjacency Matrix)과 인접 리스트(Adjacency List)의 비교를 해보세요.",
  "깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS) 알고리즘에 대해 설명하세요.",
  "그래프에서 싸이클(Cycle)을 찾는 방법은 무엇인가요?",
  "최단 경로 문제를 해결하기 위한 다익스트라 알고리즘과 벨만-포드 알고리즘의 차이를 설명하세요.",
  "최소 신장 트리(Minimum Spanning Tree)란 무엇이고, 크루스칼 알고리즘과 프림 알고리즘에 대해 설명하세요.",
  "트리(Tree)란 무엇이며 어떤 특징을 가지고 있나요?",
  "이진 트리(Binary Tree)와 이진 탐색 트리(Binary Search Tree, BST)의 차이점을 설명하세요.",
  "트리 순회 알고리즘 중 중위 순회(Inorder Traversal), 전위 순회(Preorder Traversal), 후위 순회(Postorder Traversal)에 대해 설명하세요.",
  "균형 이진 트리(Balanced Binary Tree)의 중요성은 무엇이며 AVL 트리와 레드-블랙 트리에 대해 설명하세요.",
  "이진 힙(Binary Heap)이란 무엇이고, 최소 힙(Min Heap)과 최대 힙(Max Heap)의 차이는 무엇인가요?",
  "트리의 높이(Height)와 깊이(Depth)의 개념을 설명하고, 균형 트리와 비균형 트리의 높이 차이에 대해 언급하세요.",
  "트리를 사용하여 어떻게 검색(Binary Search)을 수행할 수 있나요?",
  "트리를 사용하여 어떻게 삽입과 삭제 연산을 수행할 수 있나요?",
  "트리의 자식 노드 수에 따라 이진 트리(Binary Tree), 이진 탐색 트리(Binary Search Tree), N-진 트리(N-ary Tree)와 같은 다양한 종류의 트리가 있습니다. 각각의 특징을 설명하세요.",
  "트리를 활용한 알고리즘 및 자료구조의 예시는 어떤 것들이 있나요?",
  "정렬 알고리즘의 목적은 무엇인가요?",
  "내부 정렬(Internal Sorting)과 외부 정렬(External Sorting)의 차이는 무엇인가요?",
  "비교 기반 정렬 알고리즘(Comparison-based Sorting)과 비교하지 않는 정렬 알고리즘(Non-comparison Sorting)의 차이를 설명하세요.",
  "버블 정렬(Bubble Sort) 알고리즘에 대해 설명하세요.",
  "선택 정렬(Selection Sort) 알고리즘에 대해 설명하세요.",
  "삽입 정렬(Insertion Sort) 알고리즘에 대해 설명하세요.",
  "퀵 정렬(Quick Sort) 알고리즘에 대해 설명하세요.",
  "병합 정렬(Merge Sort) 알고리즘에 대해 설명하세요.",
  "힙 정렬(Heap Sort) 알고리즘에 대해 설명하세요.",
  "기수 정렬(Radix Sort) 알고리즘에 대해 설명하세요.",
  "정렬 알고리즘의 성능을 어떻게 측정할 수 있나요?",
  "안정적인(Stable) 정렬 알고리즘이 무엇이며 왜 중요한가요?",
  "외부 정렬(External Sorting)에서 사용되는 대표적인 알고리즘에 대해 설명하세요.",
  "정렬 알고리즘을 선택할 때 고려해야 하는 요소는 무엇인가요?",
  "비교 기반 정렬 알고리즘 중 퀵 정렬과 병합 정렬의 차이를 설명하세요.",
  "C 언어란 무엇인가요? 간단히 설명해주세요.",
  "C 언어의 역사적 배경에 대해 어떻게 아시나요?",
  "C 언어의 특징은 무엇인가요?",
  "C 언어의 데이터 타입(Data Types)에 대해 설명하세요.",
  "변수(Variables)와 상수(Constants)의 차이점을 설명하세요.",
  "C 언어에서 주석(Comments)을 작성하는 방법은 어떻게 되나요?",
  "표준 입출력 함수인 printf()와 scanf()를 어떻게 사용하나요?",
  "C 언어에서의 연산자(Operators)와 그 종류를 설명하세요.",
  "if 문과 switch 문의 차이를 설명하고, 각각의 사용 예시를 들어주세요.",
  "반복문(Loop)인 for, while, do-while의 사용법과 차이점을 설명하세요.",
  "배열(Array)과 포인터(Pointer)의 관계를 설명하세요.",
  "동적 메모리 할당(Dynamic Memory Allocation)을 위해 사용되는 함수들과 그 사용법을 설명하세요.",
  "함수(Function)의 정의와 호출 방법을 설명하세요.",
  "재귀 함수(Recursive Function)에 대해 설명하고 사용 예시를 들어주세요.",
  "구조체(Structures)와 공용체(Unions)에 대해 설명하세요.",
  "파일 처리(File Handling)를 위해 사용되는 함수들과 그 사용법을 설명하세요.",
  "가상 메모리(Virtual Memory)란 무엇인가요?",
  "가상 메모리가 필요한 이유는 무엇인가요?",
  "가상 메모리와 물리 메모리(Physical Memory)의 차이는 무엇인가요?",
  "페이지 부재(Page Fault)란 무엇이며 어떤 상황에서 발생하나요?",
  "페이지 교체 알고리즘(Page Replacement Algorithm)에 대해 설명하세요. 대표적인 알고리즘은 무엇이 있나요?",
  "페이지 테이블(Page Table)이 무엇이며 어떤 역할을 하나요?",
  "TLB(Translation Lookaside Buffer)란 무엇이며 어떤 목적으로 사용되나요?",
  "스와핑(Swapping)과 페이지 스와핑(Page Swapping)의 차이를 설명하세요.",
  "가상 메모리의 장점과 단점은 무엇인가요?",
  "Demand Paging(요구 페이징)이란 무엇이며 어떻게 동작하나요?",
  "페이지 크기(Page Size)를 결정하는 요소는 무엇이 있고, 어떻게 선택되나요?",
  "가상 주소(Virtual Address)와 물리 주소(Physical Address)의 변환 과정을 설명하세요.",
  "페이지 테이블의 구조와 동작 방식을 설명하세요.",
  "스레싱(Thrashing)이란 무엇이며 어떤 상황에서 발생하나요?",
  "가상 메모리 관리 기법 중 세그멘테이션(Segmentation)에 대해 설명하세요.",
  "메모리 계층 구조(Memory Hierarchy)란 무엇인가요?",
  "메모리 계층 구조의 목적은 무엇인가요?",
  "주 기억장치(Primary Memory)와 보조 기억장치(Secondary Memory)의 차이는 무엇인가요?",
  "메모리 계층 구조에서 주로 사용되는 기억장치의 종류는 어떤 것이 있나요?",
  "캐시 메모리(Cache Memory)가 무엇이고 어떤 역할을 하나요?",
  "캐시 미스(Cache Miss)와 캐시 히트(Cache Hit)의 개념을 설명하세요.",
  "캐시 메모리의 교체 정책(Replacement Policy)에는 어떤 것들이 있으며 각각 어떤 특징을 가지고 있나요?",
  "캐시 메모리의 연관성(Associativity)이 무엇이며 왜 중요한가요?",
  "캐시 메모리와 주 기억장치 간 데이터 전송 과정을 설명하세요.",
  "메모리 계층 구조에서 데이터의 저장 및 접근 속도에 따른 장단점은 어떻게 될까요?",
  "가상 메모리(Virtual Memory)와 메모리 계층 구조 간의 관계는 무엇인가요?",
  "메모리 계층 구조를 최적화하기 위한 방법으로 어떤 것들이 있을까요?",
  "RAM(Random Access Memory)과 ROM(Read-Only Memory)의 차이를 설명하세요.",
  "메모리 계층 구조의 발전 과정과 역사적 변화에 대해 어떤 것을 아시나요?",
  "메모리 계층 구조가 컴퓨터 성능에 어떤 영향을 미치는지 설명하세요.",
  "프로세스(Process)란 무엇인가요?",
  "스레드(Thread)란 무엇인가요?",
  "프로세스와 스레드의 주요 차이점은 무엇인가요?",
  "멀티프로세싱(Multiprocessing)과 멀티스레딩(Multithreading)의 차이를 설명하세요.",
  "프로세스 간 통신(IPC, Inter-Process Communication) 방법에는 어떤 것들이 있으며 각각의 특징을 설명하세요.",
  "스레드 간 동기화(Synchronization)가 왜 필요한가요? 어떤 문제를 해결하기 위해 사용되나요?",
  "스레드의 상태(State)에는 어떤 것들이 있으며 각각 어떤 상황에서 발생하나요?",
  "스레드 풀(Thread Pool)이란 무엇이며 어떤 장점을 가지고 있나요?",
  "프로세스와 스레드 간 공유하는 자원(Resource)에는 어떤 것들이 있고, 어떻게 관리해야 하나요?",
  "컨텍스트 스위칭(Context Switching)이란 무엇이며 어떤 상황에서 발생하나요?",
  "동시성(Concurrency)과 병렬성(Parallelism)의 차이를 설명하세요.",
  "프로세스와 스레드의 생성 및 종료 방법을 설명하세요.",
  "스레드의 우선순위(Priority)와 스케줄링(Scheduling)에 대해 설명하세요.",
  "유저 스레드(User Thread)와 커널 스레드(Kernel Thread)의 차이를 설명하세요.",
  "멀티코어 프로세서(Multi-core Processor)에서 멀티스레딩을 어떻게 활용할 수 있나요?",
  "네트워크(Network)란 무엇인가요?",
  "네트워크의 주요 목적은 무엇인가요?",
  "네트워크를 구성하는 기본 요소는 무엇인가요?",
  "LAN(Local Area Network)과 WAN(Wide Area Network)의 차이점을 설명하세요.",
  "IP 주소(IP Address)와 MAC 주소(MAC Address)의 역할과 차이를 설명하세요.",
  "TCP/IP 프로토콜 스택(TCP/IP Protocol Stack)에는 어떤 계층이 있으며 각 계층의 역할을 설명하세요.",
  "OSI 모델(OSI Model)에 대해 설명하고, 각 계층의 이름을 나열하세요.",
  "네트워크 토폴로지(Network Topology)에 대해 설명하세요. 다양한 토폴로지 종류를 언급해주세요.",
  "라우터(Router)와 스위치(Switch)의 역할과 차이를 설명하세요.",
  "서브넷(Subnet)이 무엇이며 왜 사용하나요?",
  "네트워크 보안(Network Security)에 대해 어떤 것을 아시나요?",
  "방화벽(Firewall)이란 무엇이며 왜 필요한가요?",
  "네트워크에서 데이터 전송 방식으로 유니캐스트(Unicast), 브로드캐스트(Broadcast), 멀티캐스트(Multicast)의 차이를 설명하세요.",
  "DNS(Domain Name System)이란 무엇이며 어떤 역할을 하나요?",
  "DHCP(Dynamic Host Configuration Protocol)가 무엇이며 어떻게 작동하나요?",
  "네트워크에서 Quality of Service(QoS)는 무엇이며 왜 중요한가요?",
  "네트워크에서의 라우팅(Routing)과 스위칭(Switching)에 대해 설명하세요.",
  "네트워크에서의 데이터 전송 방식으로 유선 네트워크(Wired Network)와 무선 네트워크(Wireless Network)의 차이를 설명하세요.",
  "IPv4와 IPv6의 차이와 IPv6의 장점은 무엇인가요?",
  "가상 사설망(Virtual Private Network, VPN)이란 무엇이며 어떻게 동작하나요?",
  "네트워크 관리 및 감시 도구(Network Management Tools)에 대해 어떤 것을 아시나요?",
  "클라우드 네트워킹(Cloud Networking)의 개념과 이점에 대해 설명하세요.",
  "컴퓨터에서 데이터 처리(Data Processing)란 무엇인가요?",
  "데이터 처리의 주요 단계는 어떤 것들이 있나요?",
  "CPU(Central Processing Unit)의 역할은 무엇이며, 어떻게 데이터를 처리하나요?",
  "컴퓨터에서의 데이터 저장과 관리를 위해 어떤 주요 기억장치들이 사용되나요?",
  "컴퓨터에서 데이터를 입력(Input)하는 방법에는 어떤 것들이 있나요?",
  "데이터 처리의 종류로는 어떤 것들이 있으며, 각각의 특징을 설명하세요.",
  "바이트(Byte)와 비트(Bit)의 차이를 설명하세요.",
  "데이터 압축(Data Compression)이 무엇이며, 어떤 상황에서 사용되나요?",
  "빅 데이터(Big Data) 처리에 대해 설명하세요. 어떤 도구나 기술이 사용되나요?",
  "병렬 처리(Parallel Processing)와 분산 처리(Distributed Processing)의 차이를 설명하세요.",
  "컴퓨터에서의 데이터 보안(Data Security)과 데이터 백업(Data Backup)에 대해 어떤 것을 아시나요?",
  "데이터베이스(Database)와 데이터베이스 관리 시스템(DBMS)에 대해 설명하세요.",
  "데이터 웨어하우스(Data Warehouse)와 데이터 마이닝(Data Mining)의 개념과 활용에 대해 설명하세요.",
  "머신 러닝(Machine Learning)과 딥 러닝(Deep Learning)이 데이터 처리에 어떻게 활용되나요?",
  "데이터 처리와 관련된 알고리즘 중 정렬(Sorting) 알고리즘에 대해 설명하세요.",
  "데이터베이스에서의 쿼리(Query)와 데이터 검색(Information Retrieval)에 대해 어떤 것을 아시나요?",
  "데이터 처리 과정에서 발생할 수 있는 에러와 예외 처리(Exception Handling)에 대해 설명하세요.",
  "클라우드 컴퓨팅(Cloud Computing)과 데이터 처리에 대한 연관성을 설명하세요.",
  "데이터 처리와 관련된 현재의 기술 트렌드는 무엇인가요?",
  "데이터 처리의 효율성과 성능을 향상시키기 위해 어떤 최적화 기술이 사용되나요?",
  "인코딩(Encoding)과 디코딩(Decoding)이란 무엇인가요?",
  "왜 데이터를 인코딩하거나 디코딩해야 하나요?",
  "텍스트 데이터의 인코딩과 바이너리 데이터의 인코딩의 차이점은 무엇인가요?",
  "텍스트 데이터를 인코딩하는 방법으로 주로 사용되는 인코딩 스키마(Encoding Scheme)는 어떤 것이 있나요?",
  "Base64 인코딩이란 무엇이며 어떤 상황에서 사용되나요?",
  "UTF-8과 UTF-16의 차이를 설명하세요.",
  "압축 인코딩(Compression Encoding)의 개념과 사용 사례를 설명하세요.",
  "이진 인코딩(Binary Encoding)이 어떻게 작동하나요?",
  "디코딩 과정에서 발생할 수 있는 오류와 그 해결 방법에 대해 언급하세요.",
  "인코딩과 디코딩의 성능을 향상시키기 위해 어떤 최적화 기술이 사용되나요?",
  "이미지, 오디오, 비디오 등의 멀티미디어 데이터를 인코딩하고 디코딩하는 기술은 어떻게 다를까요?",
  "데이터의 암호화(Encoding)와 복호화(Decoding)는 어떻게 동작하나요?",
  "JSON과 XML 데이터 형식을 다룰 때 인코딩과 디코딩의 중요성은 무엇인가요?",
  "네트워크 통신에서 데이터의 인코딩과 디코딩은 어떤 역할을 하며 왜 필요한가요?",
  "웹 개발에서 URL 인코딩과 디코딩이 어떻게 사용되나요?",
  "인코딩과 디코딩 과정에서 보안 문제가 발생할 수 있는 경우를 어떻게 방지할 수 있을까요?",
  "멀티스레딩 환경에서의 인코딩과 디코딩은 어떻게 관리되어야 하나요?",
  "언어 간 인코딩과 디코딩의 어려움과 해결 방법에 대해 언급하세요.",
  "XML과 JSON 인코딩 및 디코딩 라이브러리와 도구를 어떻게 선택하고 사용할 수 있나요?",
  "HTTP(Hypertext Transfer Protocol)란 무엇인가요?",
  "HTTP의 주요 역할은 무엇이며 어떤 용도로 사용되나요?",
  "HTTP와 HTTPS의 차이점은 무엇인가요?",
  "HTTP 요청 메서드(Request Methods) 중 GET과 POST의 차이를 설명하세요.",
  "HTTP 상태 코드(HTTP Status Codes) 중 몇 가지를 예를 들어 설명하세요.",
  "HTTP 헤더(Headers)는 무엇이며 어떤 정보를 포함하나요?",
  "HTTP 쿠키(Cookies)와 세션(Session)의 차이를 설명하세요.",
  "HTTP 캐싱(Caching)이란 무엇이며 왜 사용하나요?",
  "HTTP 리다이렉션(Redirection)은 어떤 경우에 발생하며 어떻게 동작하나요?",
  "HTTP 요청(Request)과 응답(Response)의 구조를 설명하세요.",
  "HTTP/1.0, HTTP/1.1, HTTP/2, HTTP/3의 차이와 개선 사항을 언급하세요.",
  "REST(Representational State Transfer)와 RESTful API에 대해 설명하세요.",
  "SOAP(Simple Object Access Protocol)와 REST의 차이를 비교 설명하세요.",
  "HTTP와 웹 보안(Web Security) 간의 관계를 어떻게 설명할 수 있나요?",
  "크로스 오리진 리소스 공유(CORS, Cross-Origin Resource Sharing)에 대해 설명하세요.",
  "HTTP 요청의 생명주기(Lifecycle)를 설명하세요.",
  "HTTP/2의 주요 특징과 이점은 무엇인가요?",
  "HTTP 헤더 필드(Http Header Fields) 중 일반 헤더, 요청 헤더, 응답 헤더, 엔터티 헤더의 차이를 설명하세요.",
  "HTTP 메서드 중 PUT, DELETE, PATCH의 용도와 사용 방법을 설명하세요.",
  "HTTP 푸시(Push)와 프리로드(Preload)에 대해 어떻게 설명할 수 있나요?",
  "웹 소켓(WebSocket)과 HTTP의 비교를 해보세요.",
  "HTTP와 관련된 보안 문제와 해결 방법에 대해 언급하세요.",
  "HTTP/3와 QUIC(Quick UDP Internet Connections) 프로토콜에 대해 설명하세요.",
  "HTTP/1.1과 HTTP/2의 헤더 압축 방식의 차이를 설명하세요.",
  "OSI(Open Systems Interconnection) 모델이란 무엇인가요?",
  "OSI 모델의 주요 목적과 장점은 무엇인가요?",
  "OSI 모델은 몇 개의 계층으로 구성되어 있으며 각 계층은 무엇을 담당하나요?",
  "OSI 모델의 각 계층은 어떤 이름으로 알려져 있으며 번호는 어떻게 부여되었나요?",
  "물리 계층(Physical Layer)의 주요 역할과 예시를 설명하세요.",
  "데이터 링크 계층(Data Link Layer)의 역할과 주요 기능은 무엇인가요?",
  "네트워크 계층(Network Layer)이 무엇이며 어떤 역할을 수행하나요?",
  "전송 계층(Transport Layer)은 어떤 기능을 하며 어떤 프로토콜을 사용하나요?",
  "세션 계층(Session Layer)의 주요 역할은 무엇이며 어떤 기능을 수행하나요?",
  "표현 계층(Presentation Layer)이란 무엇이며 데이터의 변환과 암호화를 어떻게 처리하나요?",
  "응용 계층(Application Layer)은 어떤 역할을 하며 어떤 프로토콜과 서비스를 제공하나요?",
  "각 계층의 데이터 단위(PDU, Protocol Data Unit)는 어떻게 구분되나요?",
  "OSI 모델은 어떤 표준화 기구에서 정의되었나요?",
  "OSI 모델의 각 계층에서 발생할 수 있는 문제와 해결 방법에 대해 언급하세요.",
  "TCP/IP 모델과 OSI 모델의 차이점은 무엇이며 어떻게 관련되어 있나요?",
  "네트워크 프로토콜 및 서비스가 OSI 모델에서 어떤 위치에 속하는지 설명하세요.",
  "OSI 모델을 통해 데이터가 전송되는 과정을 순서대로 설명하세요.",
  "OSI 모델의 각 계층이 하드웨어 또는 소프트웨어와 어떻게 관련되어 있는지 설명하세요.",
  "네트워크 트러블슈팅(Network Troubleshooting) 시 OSI 모델을 어떻게 활용할 수 있나요?",
  "소프트웨어 개발 주기(Software Development Lifecycle)에 대해 설명하세요.",
  "코드 품질(Code Quality)을 평가하는 방법에 대해 언급하세요.",
  "프로그래밍 언어의 선택 시 고려해야 할 요소는 무엇인가요?",
  "예외 처리(Exception Handling)의 중요성과 예외 처리 전략에 대해 설명하세요.",
  "소프트웨어 아키텍처(Software Architecture)란 무엇이며 왜 중요한가요?",
  "빌드(Build)와 배포(Deployment) 프로세스에 대해 설명하세요.",
  "컴포넌트(Component)와 모듈(Module)의 차이를 설명하세요.",
  "안전한 소프트웨어 개발을 위한 보안 원칙은 어떤 것이 있나요?",
  "소프트웨어 테스팅(Test)의 목적과 종류를 설명하세요.",
  "소프트웨어 개발에서 성능 최적화(Performance Optimization)에 어떻게 접근해야 하나요?",
  "소프트웨어 개발 팀에서 협업하는 방법과 도구에 대해 언급하세요.",
  "소프트웨어 버그(Bug)를 찾는 데 사용되는 디버깅 도구와 기법은 무엇인가요?",
  "소프트웨어 개발과 관련된 법적 책임과 라이선스(License)에 대해 설명하세요.",
  "컴퓨터 과학의 기초 개념 중 알고리즘(Algorithm)과 자료구조(Data Structure)에 대해 언급하세요.",
  "웹 개발에서 Frontend와 Backend의 역할과 기술 스택(Tech Stack)을 설명하세요.",
  "클라우드 컴퓨팅(Cloud Computing)의 장점과 사용 사례에 대해 언급하세요.",
  "머신러닝(Machine Learning)과 딥러닝(Deep Learning)의 개념과 응용 사례를 설명하세요.",
  "소프트웨어 엔지니어링 분야에서의 자격증과 교육 경로에 대해 언급하세요.",
  "소프트웨어 개발에서 코드 리팩토링(Refactoring)의 목적과 주요 기법을 설명하세요.",
  "소프트웨어 개발 프로젝트에서 프로젝트 관리(Project Management)의 중요성과 기법을 언급하세요.",
  "소프트웨어 품질 보증(Quality Assurance)과 소프트웨어 테스팅(Test)의 차이를 설명하세요.",
  "소프트웨어 개발에서의 최신 트렌드와 기술 동향에 대해 언급하세요.",
  "소프트웨어 개발 과정에서 발생하는 문제 해결과 의사소통 능력의 중요성에 대해 언급하세요.",
  "소프트웨어 개발 분야에서 자신의 경험과 프로젝트를 소개하세요.",
  "프로그래밍 언어란 무엇인가요?",
  "컴파일러(Compiler)와 인터프리터(Interpreter)의 차이는 무엇인가요?",
  "정적 언어(Static Language)와 동적 언어(Dynamic Language)의 차이를 설명하세요.",
  "변수(Variable)와 상수(Constant)의 차이를 설명하세요.",
  "데이터 타입(Data Type)에 대해 설명하고 몇 가지 예시를 들어보세요.",
  "연산자(Operator)와 연산자 우선순위(Operator Precedence)에 대해 설명하세요.",
  "조건문(Conditional Statements)과 반복문(Loop Statements)의 역할을 설명하세요.",
  "함수(Function)와 메서드(Method)의 차이를 설명하세요.",
  "재귀 함수(Recursive Function)의 개념과 사용 사례를 설명하세요.",
  "클래스(Class)와 객체(Object)의 관계를 설명하세요.",
  "상속(Inheritance)과 다형성(Polymorphism)에 대해 언급하세요.",
  "인터페이스(Interface)와 추상 클래스(Abstract Class)의 차이를 설명하세요.",
  "자료구조(Data Structure)와 알고리즘(Algorithm)을 언급하고 중요성에 대해 설명하세요.",
  "동시성(Concurrency)과 병렬성(Parallelism)의 차이를 설명하세요.",
  "메모리 관리(Memory Management)와 가비지 컬렉션(Garbage Collection)에 대해 언급하세요.",
  "컴파일 언어(Compiled Language)와 스크립트 언어(Scripting Language)의 차이를 설명하세요.",
  "프로그래밍 언어의 역사와 중요한 언어들을 언급하세요.",
  "함수형 프로그래밍(Functional Programming)과 객체지향 프로그래밍(Object-Oriented Programming)의 차이를 설명하세요.",
  "동적 타이핑(Dynamic Typing)과 정적 타이핑(Static Typing)의 장단점을 비교하세요.",
  "컴퓨터 과학에서 널리 사용되는 언어 중 하나를 선택하고 그 언어의 특징과 사용 사례를 설명하세요.",
  "프로그래밍 언어의 최신 트렌드와 미래 전망에 대해 언급하세요.",
  "알고리즘이란 무엇이며 왜 중요한가요?",
  "시간 복잡도와 공간 복잡도란 무엇이며 차이점은 무엇인가요?",
  "빅 오 표기법(Big O notation)이란 무엇이며 어떻게 사용되나요?",
  "자료구조(Data Structure)란 무엇이며 어떤 종류가 있나요?",
  "배열(Array)과 연결 리스트(Linked List)의 차이를 설명하세요.",
  "스택(Stack)과 큐(Queue)의 동작과 사용 사례에 대해 설명하세요.",
  "해시 테이블(Hash Table)이란 무엇이며 어떤 상황에서 사용하나요?",
  "트리(Tree)와 그래프(Graph)의 차이와 사용 사례를 비교하세요.",
  "깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS) 알고리즘에 대해 설명하세요.",
  "그리디 알고리즘(Greedy Algorithm)과 동적 프로그래밍(Dynamic Programming)의 차이를 설명하세요.",
  "최소 신장 트리(Minimum Spanning Tree)와 최단 경로 문제(Shortest Path Problem)를 언급하세요.",
  "정렬 알고리즘(Sorting Algorithm) 중 몇 가지를 설명하고 각각의 시간 복잡도를 언급하세요.",
  "비트 연산(Bitwise Operation)과 비트마스크(Bitmask)에 대해 설명하세요.",
  "컴퓨터 메모리 계층 구조(Memory Hierarchy)에 대해 언급하세요.",
  "스레드(Thread)와 프로세스(Process)의 차이와 멀티스레딩(Multithreading)의 장점을 설명하세요.",
  "데드락(Deadlock)이란 무엇이며 어떻게 방지할 수 있나요?",
  "네트워크 프로토콜과 OSI 모델에 대해 설명하세요.",
  "빅 데이터(Big Data)와 클라우드 컴퓨팅(Cloud Computing)에 대해 언급하세요.",
  "암호화와 보안에 관련된 주요 개념과 알고리즘을 설명하세요.",
  "소프트웨어 개발 생명 주기(Software Development Lifecycle)에 대해 언급하세요.",
  "소프트웨어 테스팅(Test)의 목적과 종류를 설명하세요.",
  "버전 관리 시스템(Version Control System)과 Git의 개념을 설명하세요.",
  "웹 개발에서 Frontend와 Backend의 역할과 기술 스택(Tech Stack)을 설명하세요.",
  "머신 러닝(Machine Learning)과 인공 지능(AI)에 대한 기본 개념을 언급하세요.",
  "애자일(Agile) 개발 방법론과 스크럼(Scrum)에 대해 설명하세요.",
  "소프트웨어 엔지니어링 분야에서의 자격증과 교육 경로에 대해 언급하세요.",
  "프로그래밍 언어와 프레임워크(Framework)의 관련성을 설명하세요.",
  "개발자의 역할과 소프트웨어 개발 팀에서의 협업 방법에 대해 언급하세요.",
  "소프트웨어 개발 분야에서의 최신 트렌드와 기술 동향에 대해 언급하세요.",
  "인코딩(Encoding)이란 무엇인가요?",
  "텍스트 인코딩(Text Encoding)과 바이너리 인코딩(Binary Encoding)의 차이는 무엇인가요?",
  "Base64 인코딩(Base64 Encoding)이란 무엇이며 어떤 상황에서 사용되나요?",
  "Base64 인코딩의 작동 원리를 설명하세요.",
  "Base64 디코딩(Base64 Decoding)은 어떻게 작동하나요?",
  "Base64 인코딩과 디코딩을 어떻게 수행하나요? (예시 코드로 설명)",
  "URL 인코딩(URL Encoding)과 URL 디코딩(URL Decoding)에 대해 설명하세요.",
  "UTF-8 인코딩(UTF-8 Encoding)이란 무엇이며 왜 널리 사용되나요?",
  "UTF-16과 UTF-32 인코딩에 대해 언급하세요.",
  "ASCII 인코딩과 확장 ASCII(Extended ASCII)에 대해 설명하세요.",
  "인코딩 오류(Encoding Error)가 발생하는 경우와 그 처리 방법을 설명하세요.",
  "압축 인코딩(Compression Encoding)과 그 중요성에 대해 언급하세요.",
  "데이터 암호화(Encoding)와 디코딩(Decoding)의 관련성을 설명하세요.",
  "유니코드(Unicode)와 문자 인코딩(Encoding)의 관계에 대해 언급하세요.",
  "Base64 인코딩을 사용한 이미지나 파일의 전송 방법을 설명하세요.",
  "멀티파트 인코딩(Multipart Encoding)과 멀티파트 디코딩(Multipart Decoding)에 대해 언급하세요.",
  "CPU 아키텍처(CPU Architecture)란 무엇인가요?",
  "CPU와 GPU의 주요 차이점은 무엇인가요?",
  "Von Neumann 아키텍처와 Harvard 아키텍처의 차이를 설명하세요.",
  "명령어 세트 아키텍처(ISA, Instruction Set Architecture)란 무엇이며 종류는 어떤 것이 있나요?",
  "레지스터(Register)와 캐시(Cache)의 역할을 설명하세요.",
  "파이프라인 처리(Pipeline Processing)의 개념과 장점을 설명하세요.",
  "슈퍼스칼라(Superscalar)와 VLIW(Very Long Instruction Word) 아키텍처의 특징을 비교하세요.",
  "멀티코어(Multi-Core) 프로세서와 하이퍼스레딩(Hyper-Threading)의 차이를 설명하세요.",
  "엔디안(Endian) 방식에 대해 설명하고, 빅 엔디안(Big Endian)과 리틀 엔디안(Little Endian)의 차이를 언급하세요.",
  "인스트럭션 파이프라인(Instruction Pipeline)에서 파이프라인 스테이지(Pipeline Stage)에 대해 설명하세요.",
  "컴퓨터 아키텍처에서 메모리 계층 구조(Memory Hierarchy)의 중요성을 설명하세요.",
  "동적 분기 예측(Dynamic Branch Prediction)과 정적 분기 예측(Static Branch Prediction)의 차이를 언급하세요.",
  "CPU 캐시(CPU Cache)의 작동 원리와 L1, L2, L3 캐시의 역할을 설명하세요.",
  "CPU 아키텍처에서 파이프라인 하자(Pipeline Hazard)와 해결 방법에 대해 언급하세요.",
  "CISC(Complex Instruction Set Computer)와 RISC(Reduced Instruction Set Computer) 아키텍처를 비교하세요.",
  "시스템 오버클럭(System Overclocking)의 장단점과 주의사항을 설명하세요.",
  "멀티프로세서 시스템(Multiprocessor System)에서 코어 간 통신과 동기화에 대해 언급하세요.",
  "파일 실행시간(File Execution Time)을 줄이기 위한 CPU 아키텍처 최적화 방법에 대해 설명하세요.",
  "CPU 아키텍처의 역사적인 발전과 중요한 마일스톤에 대해 언급하세요.",
  "클록 주기(Clock Cycle)와 클록 주파수(Clock Frequency)의 관계를 설명하세요.",
  "시스템 온 칩(SoC, System-on-Chip) 아키텍처의 특징과 장점을 설명하세요.",
  "병렬 컴퓨팅(Parallel Computing)과 SIMD(Single Instruction, Multiple Data) 아키텍처에 대해 언급하세요.",
  "컴퓨터 보안(Computer Security)이란 무엇인가요?",
  "암호화(Encryption)와 복호화(Decryption)의 개념과 중요성을 설명하세요.",
  "인증(Authentication)과 권한 부여(Authorization)의 차이를 언급하세요.",
  "바이러스(Virus), 웜(Worm), 트로이 목마(Trojan Horse), 맬웨어(Malware) 등의 악성 소프트웨어에 대해 설명하세요.",
  "방화벽(Firewall)의 역할과 종류를 설명하세요.",
  "사이버 공격 유형 중 DDoS 공격(Distributed Denial of Service Attack)과 SQL 인젝션(SQL Injection)에 대해 언급하세요.",
  "공개키 암호화(Public Key Encryption)와 개인키 암호화(Private Key Encryption)의 차이를 설명하세요.",
  "SSL/TLS 프로토콜(Secure Sockets Layer/Transport Layer Security)의 역할과 사용 사례를 설명하세요.",
  "보안 정책(Policy)과 접근 제어(Control)의 중요성을 강조하세요.",
  "소셜 엔지니어링(Social Engineering) 공격에 대해 설명하고 예방 방법을 언급하세요.",
  "컴퓨터 보안에서의 취약점(Weakness)과 취약점 분석(Vulnerability Analysis)의 중요성을 언급하세요.",
  "암호 해킹(Crypto Hacking) 공격과 사이드 채널(Side Channel) 공격에 대해 설명하세요.",
  "사용자 인증 방법 중 이중 인증(2FA, Two-Factor Authentication)과 자원 집중 관리자(SSO, Single Sign-On)의 특징을 비교하세요.",
  "비밀번호 보안을 강화하기 위한 추천 사항을 제시하세요.",
  "데이터 백업과 복구 전략(Data Backup and Recovery Strategy)에 대해 언급하세요.",
  "보안 업데이트(Security Patch)의 중요성과 주기에 대해 설명하세요.",
  "퍼블릭 와이파이(Public Wi-Fi) 사용 시 주의사항을 제시하세요.",
  "보안 사고(Incident)를 감지하고 대응하는 방법에 대해 설명하세요.",
  "블록체인(Blockchain) 기술이 보안 분야에 미치는 영향에 대해 언급하세요.",
  "크립토커런시(Cryptocurrency) 보안과 관련된 문제와 조치에 대해 설명하세요.",
  "보안 인증서(Security Certificate)와 인증 기관(Certificate Authority)의 역할을 설명하세요.",
  "IoT(Internet of Things) 보안과 관련된 도전 과제와 대응 전략에 대해 언급하세요.",
  "보안 교육 및 인식 프로그램의 중요성과 구현 방법을 설명하세요.",
  "개인 정보 보호(Privacy)와 데이터 보호(Data Protection)의 차이를 설명하세요.",
  "RISC(Reduced Instruction Set Computer)와 CISC(Complex Instruction Set Computer)의 차이점은 무엇인가요?",
  "RISC 아키텍처의 주요 특징을 설명하세요.",
  "CISC 아키텍처의 주요 특징을 설명하세요.",
  "RISC와 CISC 아키텍처의 성능 비교를 언급하세요.",
  "명령어 집합(Instruction Set)의 크기에서 RISC와 CISC의 차이를 설명하세요.",
  "파이프라인 처리(Pipeline Processing)을 RISC와 CISC에서 어떻게 구현하나요?",
  "복잡한 명령어 세트(CISC)는 어떻게 단순한 명령어 세트(RISC)보다 성능이 높을 수 있나요?",
  "어떤 유형의 작업이 RISC 아키텍처에서 더 효과적이고 어떤 유형의 작업이 CISC 아키텍처에서 더 효과적인가요?",
  "현대 CPU는 주로 RISC, CISC 또는 혼합 아키텍처를 사용하나요?",
  "RISC와 CISC 아키텍처의 역사적인 개발 과정을 설명하세요.",
  "RISC-V와 같은 오픈 소스 RISC 아키텍처의 중요성과 특징을 언급하세요.",
  "RISC 또는 CISC 아키텍처 선택 시 고려해야 할 요소는 무엇인가요?",
  "이식성과 성능을 고려할 때 어떤 상황에서 RISC 아키텍처를 선택하는 것이 좋을까요?",
  "RISC와 CISC 아키텍처를 혼합한 아키텍처인 EPIC(Explicitly Parallel Instruction Computing)에 대해 언급하세요.",
  "RISC-CISC 혼합 아키텍처에서의 명령어 실행 및 병렬 처리에 대해 설명하세요.",
  "웹 개발(Web Development)이란 무엇인가요?",
  "프론트엔드(Frontend)와 백엔드(Backend) 개발의 차이는 무엇인가요?",
  "웹 개발 프로세스의 주요 단계를 설명하세요.",
  "HTML, CSS, JavaScript의 역할과 차이를 설명하세요.",
  "웹 페이지의 구조를 만드는데 사용되는 HTML의 주요 태그를 몇 가지 언급하세요.",
  "CSS의 선택자(Selector)와 스타일링 속성(Property)을 사용하여 웹 페이지 디자인을 변경하는 방법을 설명하세요.",
  "JavaScript의 변수(Variable), 함수(Function), 및 객체(Object)에 대해 설명하세요.",
  "반응형 웹 디자인(Responsive Web Design)이란 무엇이며 왜 중요한가요?",
  "웹 접근성(Web Accessibility)과 그 중요성에 대해 언급하세요.",
  "웹 사이트의 성능 최적화를 위해 어떤 기술과 방법을 사용할 수 있나요?",
  "웹 보안(Web Security)에 대해 어떻게 생각하나요? 주요 보안 문제 중 일부를 언급하세요.",
  "웹 개발에서의 RESTful API의 개념과 활용 방법을 설명하세요.",
  "웹 개발에서의 버전 관리 시스템(Version Control System)과 Git의 사용 방법을 설명하세요.",
  "웹 프레임워크(Web Framework)와 그 중 일부를 언급하고 사용 이유를 설명하세요.",
  "웹 개발에서의 데이터베이스(Database)의 역할과 주요 유형을 언급하세요.",
  "웹 애플리케이션의 라이프사이클(Lifecycle)과 요청-응답 모델을 설명하세요.",
  "웹 개발에서의 성능 최적화를 위해 어떤 도구와 기술을 사용할 수 있나요?",
  "웹 개발에서의 테스팅(Test)과 디버깅(Debugging)의 중요성을 설명하세요.",
  "웹 개발 프로젝트에서 프론트엔드와 백엔드 개발자 간의 협업 방법을 언급하세요.",
  "웹 개발의 최신 트렌드와 기술 동향에 대해 어떻게 최신 정보를 얻나요?",
  "웹 개발자로서의 역량을 향상시키기 위해 어떤 학습 방법을 추천하나요?",
  "동시성 프로그래밍(Concurrency Programming)이란 무엇인가요?",
  "병렬 프로그래밍(Parallel Programming)과 동시성 프로그래밍의 차이점은 무엇인가요?",
  "스레드(Thread)와 프로세스(Process)의 개념과 차이를 설명하세요.",
  "동기화(Synchronization)와 비동기화(Asynchronization)의 개념을 설명하세요.",
  "뮤텍스(Mutex)와 세마포어(Semaphore)의 역할과 차이를 언급하세요.",
  "스레드 풀(Thread Pool)의 개념과 사용 이유를 설명하세요.",
  "스레드 간 통신(Inter-Thread Communication)을 위해 어떤 기법을 사용할 수 있나요?",
  "스레드와 프로세스 간 공유 메모리(Shared Memory)의 장단점을 언급하세요.",
  "데드락(Deadlock)이란 무엇이며 어떻게 발생하나요? 방지 및 해결 방법에 대해 설명하세요.",
  "교착 상태(Starvation)와 경쟁 조건(Race Condition)에 대해 언급하세요.",
  "병렬 컴퓨팅(Parallel Computing)과 멀티스레딩(Multithreading)의 차이를 설명하세요.",
  "스레드의 생애주기(Thread Lifecycle)와 각 상태에 대해 설명하세요.",
  "스레드 간 공유 자원에 대한 접근 제어(Control) 방법을 언급하세요.",
  "데이터 레이스(Data Race)와 그로 인한 문제를 어떻게 방지할 수 있나요?",
  "스레드 안전성(Thread Safety)과 관련된 개념을 설명하세요.",
  "동시성 이슈를 진단하고 해결하기 위해 어떤 도구와 기술을 사용할 수 있나요?",
  "멀티스레딩을 사용하여 어떤 유형의 작업을 효과적으로 수행할 수 있나요?",
  "동시성 프로그래밍에서 발생할 수 있는 성능 문제를 어떻게 해결할 수 있나요?",
  "동시성 프로그래밍에서의 데드락을 방지하기 위한 디자인 원칙을 설명하세요.",
  "멀티코어 프로세서(Multi-core Processor)에서 동시성 프로그래밍의 중요성을 언급하세요.",
  "Futures 및 Promises와 같은 비동기 프로그래밍 패턴에 대해 설명하세요.",
  "리눅스(Linux)란 무엇인가요?",
  "오픈 소스 소프트웨어(Open Source Software)와 리눅스의 관계를 설명하세요.",
  "리눅스 배포판(Distribution)이란 무엇이며 어떤 종류가 있나요?",
  "커널(Kernel)과 쉘(Shell)의 역할을 설명하세요.",
  "리눅스의 파일 시스템(File System) 구조를 설명하세요.",
  "터미널(Terminal) 및 콘솔(Console)의 차이점을 언급하세요.",
  "리눅스 명령어(Command) 중 일부를 예를 들어 설명하세요.",
  "파일 및 디렉터리 권한(Permission)을 설정하고 확인하는 방법을 설명하세요.",
  "프로세스(Process)와 스레드(Thread)의 차이를 설명하세요.",
  "리눅스에서의 프로세스 관리와 스케줄링(Scheduling) 방법을 언급하세요.",
  "패키지 관리자(Package Manager)와 그 역할을 설명하세요.",
  "리눅스에서의 네트워크 설정 및 관리 방법을 설명하세요.",
  "리눅스에서의 시스템 로깅 및 로그 파일 관리에 대해 언급하세요.",
  "리눅스에서의 사용자 계정 관리와 그 권한 설정 방법을 설명하세요.",
  "리눅스 서버 보안 및 방화벽 설정에 대해 언급하세요.",
  "시스템 리소스 모니터링과 성능 튜닝 방법을 설명하세요.",
  "리눅스 명령어 중 awk, sed, grep와 같은 텍스트 처리 도구에 대해 설명하세요.",
  "리눅스에서의 쉘 스크립트(Shell Scripting) 작성 및 실행 방법을 설명하세요.",
  "리눅스 클라우드 환경에서의 배포 및 관리 방법을 언급하세요.",
  "리눅스 커널 업그레이드 및 커널 모듈 관리 방법을 설명하세요.",
  "리눅스의 장점과 서버 및 임베디드 시스템에서의 주요 사용 사례를 언급하세요.",
  "운영체제(Operating System)란 무엇인가요?",
  "운영체제의 주요 목적은 무엇인가요?",
  "프로세스(Process)와 스레드(Thread)의 차이를 설명하세요.",
  "멀티태스킹(Multitasking)과 멀티프로세싱(Multiprocessing)의 개념을 설명하세요.",
  "CPU 스케줄링(Scheduling)이란 무엇이며 어떤 목적을 가지고 있나요?",
  "프로세스 상태(Ready, Running, Blocked)와 상태 전이(State Transition)에 대해 설명하세요.",
  "인터럽트(Interrupt)와 그 종류에 대해 언급하세요.",
  "가상 메모리(Virtual Memory)의 개념과 장점을 설명하세요.",
  "파일 시스템(File System)의 역할과 주요 기능을 설명하세요.",
  "동기(Synchronization)와 비동기(Asynchronization)의 차이를 설명하세요.",
  "데드락(Deadlock)이란 무엇이며 어떻게 방지할 수 있나요?",
  "쓰레싱(Thrashing)이란 무엇이며 어떻게 발생하나요? 방지 및 해결 방법을 언급하세요.",
  "페이지 교체 알고리즘(Page Replacement Algorithms) 중 일부를 언급하고 설명하세요.",
  "파일 암호화(File Encryption)와 접근 제어(Access Control)의 중요성을 설명하세요.",
  "운영체제의 종류와 각각의 특징을 언급하세요. (예: Windows, Linux, macOS)",
  "리눅스의 커널(Kernel)과 사용자 공간(User Space)의 차이를 설명하세요.",
  "프로세스 간 통신(Inter-Process Communication, IPC) 메커니즘 중 일부를 언급하고 설명하세요.",
  "운영체제의 보안 및 보호 기능에 대해 언급하세요.",
  "가상화(Virtualization)와 컨테이너화(Containerization)의 차이를 설명하세요.",
  "운영체제의 장애 복구 및 복원(Disaster Recovery) 전략을 언급하세요.",
  "운영체제 업그레이드 및 패치 관리에 대해 언급하세요.",
  "운영체제의 성능 모니터링과 최적화 방법을 설명하세요.",
  "데이터베이스(Database)란 무엇인가요?",
  "SQL과 NoSQL 데이터베이스의 차이를 설명하세요.",
  "데이터베이스 관리 시스템(DBMS)의 역할과 중요성에 대해 언급하세요.",
  "관계형 데이터베이스(Relational Database)의 특징을 설명하세요.",
  "테이블(Table)과 열(Column) 그리고 행(Row)에 대한 개념을 설명하세요.",
  "SQL(Structured Query Language)의 주요 명령어(SELECT, INSERT, UPDATE, DELETE)를 설명하세요.",
  "SQL 인덱스(Index)의 역할과 장점을 설명하세요.",
  "정규화(Normalization)와 역정규화(Denormalization)의 개념을 설명하세요.",
  "데이터베이스 트랜잭션(Transaction)의 개념과 ACID 특성을 설명하세요.",
  "데이터베이스 인덱싱(Indexing)과 그 종류에 대해 언급하세요.",
  "데이터베이스 스키마(Schema)와 데이터베이스 인스턴스(Instance)의 차이를 설명하세요.",
  "SQL Injection과 같은 보안 공격에 대해 어떻게 대응할 수 있는지 설명하세요.",
  "NoSQL 데이터베이스의 주요 유형 (문서형, 열 지향, 그래프, 키-값 등)을 언급하고 특징을 설명하세요.",
  "데이터베이스 백업 및 복원 전략을 설명하세요.",
  "클러스터링(Clustering)과 샤딩(Sharding)에 대해 설명하세요.",
  "빅 데이터와 데이터베이스의 관련성에 대해 언급하세요.",
  "트랜잭션 격리 수준(Transaction Isolation Levels) 중 몇 가지를 언급하고 설명하세요.",
  "데이터베이스 인덱스의 장단점과 언제 사용해야 하는지 설명하세요.",
  "데이터베이스 캐싱(Caching)에 대해 언급하고 사용 이유를 설명하세요.",
  "분산 데이터베이스(Distributed Database)와 데이터베이스 복제(Replication)의 차이를 설명하세요.",
  "데이터베이스에서의 정합성(Consistency)과 일관성(Consistency)의 차이를 설명하세요.",
  "소켓(Socket)이란 무엇인가요?",
  "TCP 소켓과 UDP 소켓의 차이점을 설명하세요.",
  "소켓 프로그래밍(Socket Programming)이란 무엇이며 어떤 상황에서 사용되나요?",
  "클라이언트(Client) 소켓과 서버(Server) 소켓의 역할을 설명하세요.",
  "소켓 통신(Socket Communication)의 동기(Synchronous)와 비동기(Asynchronous) 방식의 차이를 언급하세요.",
  "소켓 주소(Socket Address)와 IP 주소(IP Address)의 관계를 설명하세요.",
  "바인딩(Binding)과 리스닝(Listening) 소켓에 대해 설명하세요.",
  "소켓 연결(Connect)과 연결 수락(Accept)의 프로세스를 설명하세요.",
  "데이터를 소켓을 통해 전송하는 방법을 설명하세요.",
  "소켓에서의 에러 처리(Error Handling) 방법을 언급하세요.",
  "소켓 옵션(Socket Option)에 대해 설명하고 몇 가지 예를 들어보세요.",
  "멀티스레드(Multithread) 또는 멀티프로세스(Multiprocess) 환경에서의 소켓 프로그래밍에 대한 고려 사항을 언급하세요.",
  "비동기 소켓 통신을 위해 어떤 기술이나 라이브러리를 사용할 수 있나요?",
  "소켓 보안 및 암호화에 대한 고려 사항을 설명하세요.",
  "웹 소켓(WebSocket)이란 무엇이며 어떻게 작동하나요?",
  "소켓 프로그래밍에서의 성능 최적화를 위한 방법을 언급하세요.",
  "네트워크 통신에서의 지연(Latency)과 대역폭(Bandwidth)에 대한 이해를 언급하세요.",
  "본인이 개발한 소켓 기반 애플리케이션에서 발생한 문제를 해결한 경험을 공유해주세요.",
  "IPv4와 IPv6 간의 호환성과 전환(Transition)에 대해 설명하세요.",
  "소켓 프로그래밍에서의 스레드 안전성(Thread Safety)에 대한 고려 사항을 언급하세요.",
];

export default topics;
